### ISSUE TITLE
Same statement used for if and else

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/fuse-springboot-circuit-breaker-booster#3]
https://github.com/jboss-fuse/fuse-springboot-circuit-breaker-booster/blob/b756f9ed0ac973b04772977a7208edf7446d4882/greetings-service/src/main/resources/static/components/hystrixCommand/hystrixCommand.js#L121-L125

A bug on one line? Or it is the same and condition can be removed?

**Comment by valdar** [comment]
If it is a bug, is a bug upstream.
Please report it here https://github.com/Netflix-Skunkworks/hystrix-dashboard

**Comment by apupier** [comment]
you mean that the code is duplicated?

**Comment by apupier** [comment]
created https://github.com/Netflix-Skunkworks/hystrix-dashboard/issues/3
